---
- name: Copy files from local to remote
  hosts: Ubuntu
  gather_facts: False
  vars_prompt:
          - name: file
            prompt: "Enter the path to the file you want to copy to your machines"
            private: no
          
          - name: transfer
            prompt: "Where do you want this file to be located in your servers?"
            private: no
  tasks:
          - name: copy SchoolLab file from local to ubuntu machine
            copy:
                    src: "{{ file }}"
                    dest: "{{ transfer }}"

          - name: pause 10 seconds
            pause:
                    seconds: 10
   
