---
- name: Copy files from local to remote
  hosts: School
  vars_prompt:
          - name: file_directory
            prompt: "Enter the path to the file"
            private: no

          - name: file
            prompt: "Enter the file name"
            private: no

          - name: destination
            prompt: "Where do you want this file to be located in your servers?"
            private: no
  tasks:
          - name: check if file exists
            stat:
                    path: "'{{destination }}'/'{{ file }}'"
            register: file_exists
            
          - name: copy file 
            become: false
            copy:
                    src: "{{ file_directory }}/{{ file }}"
                    dest: "{{ destination }}"
            when: file_exists.stat.exists == false
