---
- name: disbale SELINUX
  hosts: parallels
  become: true
  tasks:
          - name: disbale selinux
            replace:
                    dest: /etc/selinux/config
                    regexp: 'SELINUX=enforcing'
                    replace: 'SELINUX=disabled'
                    backup: yes
