#!/bin/bash


echo "What server would you like to ping using Ansible"
read serv;



printf "You chose to ping $serv\n" 

echo "Is this correct? (y/n)"

read answr;
while (( answr != 'n' || answr != 'N' ))
do 
    read answr;
    if (( answr == 'n' || answr == 'N' ))
    then
	    break
    fi
    ansible -m ping $serv;

done 



