---
# tasks file for roles/user
############## Creating Sudo Users ######################
- name: add user to  sudo group 
  become: True
  user:
         name: "{{ item }}"
         state: present
         password: "{{ password }}"
         groups: sudo 
         system: no
         createhome: yes
  with_items: "{{ users }}"
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "CentOS" or ansible_distribution == "Fedora"

##############  Enable Passwordless Sudo  #####################
- name: add passwordless sudo to users
  become: true
  lineinfile: 
         dest: "/etc/sudoers"
         state: present
         regexp: "^%sudo"
         line: "%sudo ALL=(ALL) NOPASSWD:ALL"
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "CentOS" or ansible_distribution == "Fedora"
