---
# tasks file for roles/upgrade
#
#
- name: install packages on ubuntu machine
  apt: name=git state=absent update_cache=true
  when: ansible_distribution == "Ubuntu"
  register: ubuntu_task_result

- name: update package on fedora machine
  dnf: name=tree state=absent update_cache=true
  when: ansible_distribution == "Fedora"
  register: fedora_task_result
 
